Bj 2893
CognitiveScale/cortex-certifai-examples pull request #70
Opened 2020-11-23 09:35 UTC by bjesudasan-CS

2020-11-23 09:44 UTC, bjesudasan-CS commented
Ran the notebook in local as well as a Hosted Notebook. No issues observed.

2020-11-23 13:52 UTC, cdraper-CS requested changes
We'd need a successful run through to merge this - there's error output rather than successful run.

2020-12-01 22:19 UTC, cdraper-CS approved these changes

2020-12-02 14:52 UTC, akumar-cs approved these changes
looks good. all output is present

2020-12-02 14:53 UTC, merged